### ISSUE TITLE
怎么变得这么丑

### ISSUE THREAD

**Issue by bestK** [jaywcjlove/oscnews#15]
![image](https://user-images.githubusercontent.com/14979305/43696152-439118a2-996f-11e8-99c7-7bf11b7858c1.png)

**Comment by jaywcjlove** [comment]
你没有安装错误吧 @bestK 

![image](https://user-images.githubusercontent.com/1680273/43699077-c8879364-997f-11e8-8922-db71d51e0312.png)

我这里不是按钮的设计呢

**Comment by jiubujian** [comment]
我也是这样

**Comment by jaywcjlove** [comment]
@jiubujian 你们用的Chrome浏览器什么版本？插件是最新的版本吗？

**Comment by jaywcjlove** [comment]
清除一下缓存试一试？

**Comment by jaywcjlove** [comment]
@bestK @jiubujian 我清除缓存看到了，回头更改

**Comment by jaywcjlove** [comment]
发布了 [oscnews v1.11.0](https://chrome.google.com/webstore/detail/oscnews/iheapfheanfjcemgneblljhaebonakbg)
