### ISSUE TITLE
标签兰】栏的 kkt 是什么？

### ISSUE THREAD

**Issue by bestK** [jaywcjlove/oscnews#20]
![image](https://user-images.githubusercontent.com/14979305/53727980-84833880-3eac-11e9-9433-7d125d621cee.png)

**Comment by jaywcjlove** [comment]
这个是我搞的，React 手脚架工具 [kkt](https://github.com/jaywcjlove/kkt)  和 React服务端渲染工具 [kkt-ssr](https://github.com/jaywcjlove/kkt-ssr) 应该是其中一个吧。

**Comment by whtiehack** [comment]
![image](https://user-images.githubusercontent.com/12741016/53853782-d25d8500-4001-11e9-9d57-3c8e55bc74af.png)

**Comment by jaywcjlove** [comment]
@whtiehack 啊失误，了解了原来是这个问题

**Comment by jaywcjlove** [comment]
翻墙工具全部不能用，没有办法发布了
@bestK @whtiehack

**Comment by whtiehack** [comment]
v2ray     https://github.com/whtiehack/myhero

**Comment by jaywcjlove** [comment]
@bestK 已发布
