### ISSUE TITLE
bug!!!!

### ISSUE THREAD

**Issue by maintheme-mili** [jaywcjlove/oscnews#23]
使用插件内部搜索的内容在切换开发文档或者其他页面    之前浏览的页面的历史记录全没了

**Comment by whtiehack** [comment]
你倒是描述清楚呀。。。

**Comment by jaywcjlove** [comment]
@maintheme-mili 
![image](https://user-images.githubusercontent.com/1680273/56566372-0823f080-65e5-11e9-8a3d-ad5d1292cc7e.png)

别点击错了，这里有个清理按钮。

**Comment by maintheme-mili** [comment]
![2019-04-23_181749](https://user-images.githubusercontent.com/37646154/56573868-9358b280-65f4-11e9-862f-c887be524282.png)
![2019-04-23_181802](https://user-images.githubusercontent.com/37646154/56573871-95227600-65f4-11e9-99aa-771ca5af27e2.png)
![2019-04-23_181839](https://user-images.githubusercontent.com/37646154/56573877-981d6680-65f4-11e9-8084-c08e753a3a1e.png)

**Comment by maintheme-mili** [comment]
chrom插件内的搜索 然后点一个网页 然后切历史记录  是没有的  就算有也是chrom插件的初始页面 找不到那个页面

**Comment by maintheme-mili** [comment]
我之前用这个搜索 找到了一篇文章 不小心切到历史记录 忘了存书签 然后怎么也找不到拉= = 难受

**Comment by jaywcjlove** [comment]
@maintheme-mili 我那个历史记录是读取，的 Chrome 历史记录，插件内搜索，是放到 iframe 里面访问，估计不记录吧。搜索搞个设置，新选项卡打开得了。

**Comment by maintheme-mili** [comment]
还有还有 如果能自定义壁纸就好啦  哈哈哈哈

**Comment by maintheme-mili** [comment]
https://wht.im/ 搜索的话可以链接到这里  如果可以的话 我也不知道可以不可以 我只是觉得这个搜索很好用哈哈

**Comment by jaywcjlove** [comment]
@maintheme-mili 这样，这个工具就太臃肿了吧。

**Comment by maintheme-mili** [comment]
搜完 不用iframe 跳到新的页面啊

**Comment by maintheme-mili** [comment]
但是除了搜索 其他的使用iframe还挺方便的 比如地图 翻译什么的

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/oscnews/issues/11
