### ISSUE TITLE
搜索小bug

### ISSUE THREAD

**Issue by 1179325921** [jaywcjlove/oscnews#25]
导航栏搜索，选技术，linux命令，搜索报错

**Comment by jaywcjlove** [comment]
@1179325921 ?没有明白什么意思

**Comment by 1179325921** [comment]
![image](https://user-images.githubusercontent.com/39483844/57013525-86fcd700-6c3e-11e9-81ec-b6d352e73b6f.png)

**Comment by jaywcjlove** [comment]
@1179325921 哦这个是部署在GitHub，偶尔需要翻墙访问，嵌套的网页打不开。

![image](https://user-images.githubusercontent.com/1680273/57021564-2f229800-6c5f-11e9-919d-e420edda47e2.png)

**Comment by 1179325921** [comment]
ok,thank you
