### ISSUE TITLE
标签页显示全部空白

### ISSUE THREAD

**Issue by ZUOXIANGE** [jaywcjlove/oscnews#29]
控制台有两个报错
Unexpected token < in JSON at position 11
Error handling response: SyntaxError: Unexpected token < in JSON at position 11

现在已经完全无法使用了

**Comment by jaywcjlove** [comment]
@ZUOXIANGE 清空缓存，这里缓存了数据

![image](https://user-images.githubusercontent.com/1680273/59596810-00875080-912b-11e9-977d-df88f33acd7f.png)

**Comment by jaywcjlove** [comment]
@ZUOXIANGE 可以如下图操作一下。
![image](https://user-images.githubusercontent.com/1680273/59596929-3af0ed80-912b-11e9-8dbd-6bbb1eb57ae1.png)

**Comment by ZUOXIANGE** [comment]
可以了,谢谢

**Comment by root-i** [comment]
清除了缓存，闪了一下又是一片空白，是否与我给Chrome添加了注册表有关？
![image](https://user-images.githubusercontent.com/26275913/59958646-a0066380-94dc-11e9-89ac-47057cb4672e.png)

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/59959422-6ee06000-94e9-11e9-8f44-a6eea8ec87f5.png)

你可以看一下这里有没有，或者清除浏览器全部缓存试一试。

**Comment by root-i** [comment]
> ![image](https://user-images.githubusercontent.com/1680273/59959422-6ee06000-94e9-11e9-8f44-a6eea8ec87f5.png)
> 
> 你可以看一下这里有没有，或者清除浏览器全部缓存试一试。

现在能够使用其他的功能了
除了这里两个fetch 错误
只有点了趋势榜的时候，才会白屏
> CORS policy: No 'Access-Control-Allow-Origin'

![image](https://user-images.githubusercontent.com/26275913/59971848-c7c9fa00-95b6-11e9-932f-b3c7dbdeab2c.png)

**Comment by jaywcjlove** [comment]
你这个是跨域的感觉。不知道，我测试了一下不窜在这个问题呢。你对比一下你的版本。
