### ISSUE TITLE
edge chromium 趋势榜页面刷不出来

### ISSUE THREAD

**Issue by icoder528** [jaywcjlove/oscnews#33]
直接加载chrome的插件

**Comment by jaywcjlove** [comment]
@icoder528 刚测试了没有问题，`edge chromium` 我没有环境不好测试具体报什么错误。你对比一下应用商店，最新版本。

你可以看一下这里 https://github.com/jaywcjlove/oscnews/issues/29 也许能解决你的问题。

**Comment by icoder528** [comment]
之前是指向到chrome使用的插件不行，现在直接打开chrome的插件商店安装在edge chromium 上可以了
