### ISSUE TITLE
清单页有两个svg资源加载失败，应该是TODO的check和uncheck图标

### ISSUE THREAD

**Issue by GuaiShu** [jaywcjlove/oscnews#36]
下面这两个svg资源加载失败，导致清单前面没有选择框，不知道加载失败是什么原因
GET chrome-extension://iheapfheanfjcemgneblljhaebonakbg/static/css/static/media/todo-unchecked.6e30a532.svg net::ERR_FILE_NOT_FOUND
GET chrome-extension://iheapfheanfjcemgneblljhaebonakbg/static/css/static/media/todo-checked.869b2b3b.svg net::ERR_FILE_NOT_FOUND

如图所示：
![image](https://user-images.githubusercontent.com/14322982/62524289-eaaf2580-b867-11e9-965b-29bc3c204291.png)

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/oscnews/issues/32 已经修复了，但是最近不知道什么原因翻墙工具一直访问不了Google 账号进行发布，你可以开发模式先用起来。

**Comment by jaywcjlove** [comment]
版本更新问题 #38
