### ISSUE TITLE
GitHub Trending 无法正常更新

### ISSUE THREAD

**Issue by ZUOXIANGE** [jaywcjlove/oscnews#37]
star数量没有显示

**Comment by jaywcjlove** [comment]
@ZUOXIANGE 了解

**Comment by ZUOXIANGE** [comment]
现在完全不显示了...

**Comment by jaywcjlove** [comment]
@ZUOXIANGE 他们在发布改版，去爬数据的时候要改变规则。等发布完，再改。
![image](https://user-images.githubusercontent.com/1680273/64317849-5ad9d400-cfeb-11e9-9ef4-3cc69c866bbb.png)

**Comment by ZUOXIANGE** [comment]
OK

**Comment by jaywcjlove** [comment]
更新 #38
