### ISSUE TITLE
新版本更新问题

### ISSUE THREAD

**Issue by jaywcjlove** [jaywcjlove/oscnews#38]
由于无法更新发布新版本，只能开发模式使用。

**Comment by ZUOXIANGE** [comment]
why?

**Comment by jaywcjlove** [comment]
@ZUOXIANGE 没有购买到好的翻墙工具，发布页面一直打不开，不知道为什么。

**Comment by ZUOXIANGE** [comment]
我一直用的这个[holytech](https://store.holytech.tech/aff.php?aff=1949),V2Ray比较稳定,SS在最近国庆这段时间不太稳定.

这是我的V2Ray订阅地址https://subs.holytech.bid/osubscribe.php?sid=35596&token=thKFYzGAJHm7

**Comment by ZUOXIANGE** [comment]
@jaywcjlove 怎么还没更新呢?使用我提供的V2Ray订阅地址翻墙啊

**Comment by jaywcjlove** [comment]
@ZUOXIANGE 不知如何使用

**Comment by ZUOXIANGE** [comment]
下载[这个](https://github.com/2dust/v2rayN/releases/tag/2.41),添加我的订阅地址,然后更新订阅获取服务器节点.开启http代理,选择代理模式和节点就行了.参考[这个](https://store.holytech.tech/knowledgebase.php?action=displayarticle&id=28)

**Comment by jaywcjlove** [comment]
@ZUOXIANGE 我没有Windows，我的是Mac ，应该使用这个教程 https://store.holytech.tech/knowledgebase.php?action=displayarticle&id=18

**Comment by ZUOXIANGE** [comment]
Mac使用[这个](https://store.holytech.tech/knowledgebase.php?action=displayarticle&id=27)

**Comment by wsgzao** [comment]
@jaywcjlove 你方便的话可以发邮件给我，我之前在v2ex早期付费购买了vpnso和shadowsocks.com的服务，目前已经从上海跳槽到了新加坡，暂时不再使用永久服务了。我可以把自己的付费账号无偿借你使用，实测70周年期间服务依然坚挺，感谢你持续更新技术Blog和新版本插件

**Comment by jaywcjlove** [comment]
@wsgzao 推荐一个稳定的渠道？我自己购买就好借用不是长久之计，现在好麻烦，总是断断续续的。

**Comment by wsgzao** [comment]
@jaywcjlove 上面两个都是和曲径、GreenVPN差不多时期开始的，始于2013-2014年，还有一部分高质量的提供商已经不开放注册了，服务好现有用户好好活下去可能更加重要。你也可以先用我的付费账号临时过渡，等你买到了心仪的服务就好了，macOS比较好用的客户端基本就是V2rayU或者Outline

**Comment by jaywcjlove** [comment]
新版已发布 @wsgzao  @ZUOXIANGE 

https://github.com/jaywcjlove/oscnews/releases/tag/v1.14.0

[![](http://jaywcjlove.github.io/sb/download/chrome-web-store.svg)](https://chrome.google.com/webstore/detail/oscnews/iheapfheanfjcemgneblljhaebonakbg)

**Comment by VanHelxing** [comment]
我的 Trending 页面项目没有描述 
![image](https://user-images.githubusercontent.com/17839097/109740656-95cfbe80-7c06-11eb-85d0-2fb457122459.png)

**Comment by VanHelxing** [comment]
> 我的 Trending 页面项目没有描述
> ![image](https://user-images.githubusercontent.com/17839097/109740656-95cfbe80-7c06-11eb-85d0-2fb457122459.png)

1.14.0版本的
