### ISSUE TITLE
GitHub趋势榜出现NaN

### ISSUE THREAD

**Issue by ZUOXIANGE** [jaywcjlove/oscnews#39]
需要改一下解析规则

**Comment by jaywcjlove** [comment]
刚发布的 https://github.com/jaywcjlove/oscnews/issues/38 不知道你更新没有 @ZUOXIANGE 我这边最新版没有问题的样子

**Comment by ZUOXIANGE** [comment]
我是1.14.0
![image](https://user-images.githubusercontent.com/20124439/68357158-65315f00-014f-11ea-9585-fa99a352be78.png)

**Comment by jaywcjlove** [comment]
@ZUOXIANGE 我也是，我没有问题的样子 哪儿出现了 NaN 呢？

**Comment by ZUOXIANGE** [comment]
我上边附带了图片?

**Comment by jaywcjlove** [comment]
@ZUOXIANGE 看到了，估计人家又更新了网站，这个要同步更新一下。

**Comment by ZUOXIANGE** [comment]
建议还是优化为16.7k展示,数字太大不太容易阅读 @jaywcjlove 
![image](https://user-images.githubusercontent.com/20124439/68725876-bed7d480-05fa-11ea-9b80-ec94758fed84.png)
