### ISSUE TITLE
后端工具能否添加DotNet

### ISSUE THREAD

**Issue by RocherKong** [jaywcjlove/oscnews#4]
https://docs.microsoft.com/zh-cn/dotnet/welcome
https://www.microsoft.com/net/download/windows

**Comment by jaywcjlove** [comment]
@RocherKong no problem

**Comment by jaywcjlove** [comment]
@RocherKong 已经添加，等待发版本吧！

或者你开发模式先尝试，或者你是使用web版本 http://jaywcjlove.github.io/dev-site/

**Comment by RocherKong** [comment]
ok,等待你的发布版。
