### ISSUE TITLE
趋势榜报错

### ISSUE THREAD

**Issue by fengzhongyun1992** [jaywcjlove/oscnews#53]
chrome: 版本 86.0.4240.75（正式版本） （64 位）
oscnews 版本：1.15.0

报错：
选择趋势榜，加载失败，然后整个页面白屏

![屏幕截图 2020-10-16 093959](https://user-images.githubusercontent.com/20684744/96203351-43ae3980-0f94-11eb-9c72-a03054bafdd8.png)

**Comment by jaywcjlove** [comment]
@fengzhongyun1992 这个趋势榜是爬虫，爬 GitHub 的页面，然后解析出来的， Github页面更新了，就容易报错。

所以考虑是不是拿掉？

**Comment by wanhuasong** [comment]
这个问题什么时候修复一下呢

**Comment by jaywcjlove** [comment]
@wanhuasong 前面修复过了，估计页面又更新了

**Comment by fengzhongyun1992** [comment]
https://github.com/fengzhongyun1992/oscnews

这个是我自己修复的，去掉了fork数，然后把所有的链接添加了 _target  😄
