### ISSUE TITLE
OSNews主页报错 TypeError: e.map is not a function

### ISSUE THREAD

**Issue by ShrekerNil** [jaywcjlove/oscnews#56]
主页加载Github趋势报错, 之后显示空白页 

TypeError: e.map is not a function

![OSNews报错](https://user-images.githubusercontent.com/6695450/102006436-0ed41e00-3d5c-11eb-89d9-8473b7072bd0.png)

**Comment by jaywcjlove** [comment]
#39 #38 #29 @ShrekerNil 原因是 github网站发生了变更，这个是爬虫爬的，网站变了要跟着变
