### ISSUE TITLE
趋势榜显示不了？

### ISSUE THREAD

**Issue by skyhdj** [jaywcjlove/oscnews#57]
当你选择趋势榜之后，形式几秒钟loading.....就没了  不知道是不是我的问题

**Comment by jaywcjlove** [comment]
#38  不是你的问题，趋势榜是爬虫爬的， 官网更新了之后要跟着更新爬虫。 在考虑这个玩意儿是不是要去掉呢

**Comment by jaywcjlove** [comment]
@skyhdj
