### ISSUE TITLE
点击趋势榜tab，报错

### ISSUE THREAD

**Issue by wz930206** [jaywcjlove/oscnews#74]
![image](https://user-images.githubusercontent.com/37261842/123588246-0e900180-d81a-11eb-9edc-5d505e2386a9.png)
![image](https://user-images.githubusercontent.com/37261842/123588304-24052b80-d81a-11eb-9caa-706494f1a6e3.png)

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/oscnews/issues/65

准备把这个玩意儿删除的。 GitHub 更新，我们就要更新。
